# -*- coding: utf-8 -*-
"""Generic Medicines

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q6KPHLfnFJXZITH9MnfN6JLq1HBYynU1
"""

import pandas as pd
meds_db = pd.read_csv("https://res.cloudinary.com/dp6tqc0bs/raw/upload/v1667057203/Generic_Medicines_Data_-_Sheet1_tkja6a.csv")
meds_db_name_list = meds_db['Generic Name'].tolist()
meds_db_price_list = meds_db['MRP'].tolist()

checkExist = input("Enter the name of the salt you wish to search")

small_meds_list = []
small_price_list = []
i=-1

for med in meds_db_name_list:
  i+=1
  if(checkExist in med):
    small_meds_list.append(med)
    small_price_list.append(meds_db_price_list[i])

res = {}
for key in small_meds_list:
    for value in small_price_list:
        res[key] = value
        small_price_list.remove(value)
        break

print(res)

